### ISSUE TITLE
Boolector Backend Substitution Function

### ISSUE THREAD

**Issue by fangwenji** [stanford-centaur/smt-switch#303]
![image](https://user-images.githubusercontent.com/44700913/193447410-0a6c9b89-7801-4b62-be9e-e857f8d669ac.png)
Currently, the subsitution function in boolector solver backend doesn't support the term-->term substitution as the Pysmt does. I would like to ask that if I want to use the term-to-term substitution, is there any potential method? And when will the boolector solver support this kind of subsititution? Thank you so much!

**Comment by yoni206** [comment]
Thanks for this question.
You might want to check out the `SubstitutionWalker`, which allows you to perform arbitrary substitutions.
Here is an example of its usage:
https://github.com/stanford-centaur/smt-switch/blob/master/tests/unit/unit-substitute.cpp#L108

Feel free to follow up with more questions, we are happy to help.

**Comment by fangwenji** [comment]
That really helps! Thank you so much for your kind assistance!
