### ISSUE TITLE
Parse a smt file into smt-switch terms

### ISSUE THREAD

**Issue by fangwenji** [stanford-centaur/smt-switch#304]
![image](https://user-images.githubusercontent.com/44700913/194715976-6e1134c4-7e3b-4e39-822d-f8461fe4dc85.png)
I'm parsing an smt file got from SyGuS and cvc5 above, and I would like to ask how I can obtain the smt::term formula shown in the red frame in the figure? (Just like the function behavior in PySMT --> TSSmtLibParser --> get_fs_fname) Thank you so much for your assistance!

**Comment by yoni206** [comment]
Hi and thanks for the question.
We do have an SMT-LIB parser:
https://github.com/stanford-centaur/smt-switch/blob/master/include/smtlib_reader.h

But it parses SMT-LIB files and runs the commands in them.

@makaimann is there an easy way to retrieve a term from `SmtLibReader`?

**Comment by makaimann** [comment]
Hello and yes, thanks for the question! Unfortunately there's no easy way right now to get a term from smt-lib input right now. The parser could certainly be extended to support that but I don't have the bandwidth to add that feature right now. Sorry about that... I agree that this would be a very nice thing to have. MathSAT's parsing API allows you to do that for what it's worth.

**Comment by fangwenji** [comment]
Got it! Thank you so much for your support and suggustions.
