### ISSUE TITLE
Calling `to_int` on a bitvector of size 1 causes a crash

### ISSUE THREAD

**Issue by zyedidia** [stanford-centaur/smt-switch#308]
It seems like `to_int` assumes that the bitvector gets converted to a string of the form `#bxxx`, but for bitvectors of size 1 it is actually `true` or `false` (at least when using the bitwuzla solver). For example, the following code causes a crash in `to_int`:

```cpp
SmtSolver solver = BitwuzlaSolverFactory::create(false);
solver->set_opt("produce-models", "true");
solver->set_opt("incremental", "true");

Sort sort = solver->make_sort(BV, 1);
Term x = solver->make_symbol("x", sort);
solver->check_sat();
uint64_t i = solver->get_value(x)->to_int();
std::cout << i << "\n";
```

I would instead expect `to_int` to return `0` or `1`.

**Comment by yoni206** [comment]
Thanks for posting the issue, I'll look into it.

**Comment by yoni206** [comment]
We are having some issues with CI at the moment, but once #309 is merged, this issued should be fixed.
