### ISSUE TITLE
How to covert bit vector 1 term expressions to boolean term expressions?

### ISSUE THREAD

**Issue by fangwenji** [stanford-centaur/smt-switch#314]
Hi,
I'm currently using the cvc5 solver, which distinguishes the boolean and bv1 sorts. So I would like to ask that is there a way to convert bv1 terms to boolean terms, and conversely, from boolean to bv1?

Thank you so much for your time!

**Comment by yoni206** [comment]
Hi,

Thanks for your question.

A simple solution can be using `ite`s.
In SMT-LIB this would look like this:

```
(ite (= x (_ bv1 1)) true false)
(ite (= x true) (_ bv1 1) (_ bv0 1))
```

And the corresponding smt-switch terms can be constructed.
Hope this helps, and please let me know if you have any other questions.

**Comment by fangwenji** [comment]
Got it! Thank you so much for your help!
