### ISSUE TITLE
Switch default branch to main

### ISSUE THREAD

**Issue by CyanoKobalamyne** [stanford-centaur/smt-switch#342]
We should rename the `master` branch to `main`. We already have a stale `main`, so it should just be fast-forwarded and then we can make it the default (and delete `master`). See here for the rationale: https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/. It is very confusing that right now we have both a `master` and a `main`.

**Comment by yoni206** [comment]
I am in favor of this! If @Clark Barrett ***@***.***> also
supports it, then Aron, do you know how to?

**Comment by barrettcw** [comment]
Yes let's do this

**Comment by CyanoKobalamyne** [comment]
Done!
