### ISSUE TITLE
Linker for CVC5 requires x86-64

### ISSUE THREAD

**Issue by iblumenfeld** [stanford-centaur/smt-switch#358]
I'm getting an error trying to run the setup script on Apple silicon because the CVC5 build seems to require x86-64.  I have CVC5 already installed fine as a standalone executable, but there seems to be some issue with the smt-switch version of the config that doesn't permit this.

`cvc5::internal::prop::CadicalSolver::isFixed(unsigned long long) const in libcvc5.a[110](cadical.cpp.o)
ld: symbol(s) not found for architecture x86_64
c++: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by CyanoKobalamyne** [comment]
Thanks for the report. I am not able to reproduce this. See this run for an example: https://github.com/stanford-centaur/smt-switch/actions/runs/11601894545/job/32305661197.

Could you give some more details about your setup? What commands are you running exactly?

**Comment by CyanoKobalamyne** [comment]
Oh I see. Are you passing any arguments to the script? Just so that I can try to run the exact same thing.

**Comment by iblumenfeld** [comment]
I had not passed any arguments.

**Comment by CyanoKobalamyne** [comment]
We were able to figure this out offline. Turns out that some builds of CMake (the Homebrew ones?) run in Rosetta (Intel compatibility mode) and try to build everything for `x86_64` instead of the native `arm64`. Using the official universal binary from the CMake website solves the issue.
